---
version: '3'
services:
  umami:
    container_name: umami-core
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_TYPE=postgresql
        - SKIP_DB_CHECK=1
        - BASE_PATH=${BASE_PATH}
        - FORCE_SSL=${FORCE_SSL}
    networks:
      - dip-ict-airflow_webnet
      - internalnet
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
      CLIENT_IP_HEADER: ${CLIENT_IP_HEADER}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - internalnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:
networks:
  dip-ict-airflow_webnet:
    external: true
  internalnet: